apiVersion: v1
kind: Service

metadata:
  name: snake-game-service
  labels:
    app: snake-game

spec:
  type: LoadBalancer

  ports:
    - port: 4000
      targetPort: 4000
      protocol: TCP
      name: http

  selector:
    app: snake-game
